const queryToT9 = require('./../controllers/services/t9');

describe("Should return the correct response when", () => {
    test("we have a even input length", () => {
      const value = "2345";
      const response = queryToT9(value);
      const expectedResult = [
        "adgj",
        "adgk",
        "adgl",
        "adhj",
        "adhk",
        "adhl",
        "adij",
        "adik",
        "adil",
        "aegj",
        "aegk",
        "aegl",
        "aehj",
        "aehk",
        "aehl",
        "aeij",
        "aeik",
        "aeil",
        "afgj",
        "afgk",
        "afgl",
        "afhj",
        "afhk",
        "afhl",
        "afij",
        "afik",
        "afil",
        "bdgj",
        "bdgk",
        "bdgl",
        "bdhj",
        "bdhk",
        "bdhl",
        "bdij",
        "bdik",
        "bdil",
        "begj",
        "begk",
        "begl",
        "behj",
        "behk",
        "behl",
        "beij",
        "beik",
        "beil",
        "bfgj",
        "bfgk",
        "bfgl",
        "bfhj",
        "bfhk",
        "bfhl",
        "bfij",
        "bfik",
        "bfil",
        "cdgj",
        "cdgk",
        "cdgl",
        "cdhj",
        "cdhk",
        "cdhl",
        "cdij",
        "cdik",
        "cdil",
        "cegj",
        "cegk",
        "cegl",
        "cehj",
        "cehk",
        "cehl",
        "ceij",
        "ceik",
        "ceil",
        "cfgj",
        "cfgk",
        "cfgl",
        "cfhj",
        "cfhk",
        "cfhl",
        "cfij",
        "cfik",
        "cfil"
      ];
  
      expect(response).toEqual(expectedResult);
    });
  
    test("we have a odd input length", () => {
      const value = "233";
      const response = queryToT9(value);
      const expectedResult = [
        "add",
        "ade",
        "adf",
        "aed",
        "aee",
        "aef",
        "afd",
        "afe",
        "aff",
        "bdd",
        "bde",
        "bdf",
        "bed",
        "bee",
        "bef",
        "bfd",
        "bfe",
        "bff",
        "cdd",
        "cde",
        "cdf",
        "ced",
        "cee",
        "cef",
        "cfd",
        "cfe",
        "cff"
      ];
  
      expect(response).toEqual(expectedResult);
    });
  });
  